name: Missing Translations CI

on: [pull_request, workflow_dispatch]

jobs:
  php-tests:
    name: Suite (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system:
          - ubuntu-22.04
        php-versions:
          - "8.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Check code style
        run: |
          composer lint:check
