name: Goedemiddag CI

on:
  push:

jobs:
  php-tests:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        laravel: [ ^10.0, ^11.0, ^12.0 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
          - laravel: ^12.0
            testbench: ^10.0
        exclude:
          - php: 8.1
            laravel: ^11.0
          - php: 8.1
            laravel: ^12.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Check code style
        run: |
          composer lint:check
